apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: graphql-engine
  name: graphql-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: graphql-engine
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: graphql-engine
    spec:
      containers:
        - args:
            - --name=app
            - --playground
            - --indexer=http://subquery-node:3000
          env:
            - name: DB_DATABASE
              value: postgres
            - name: DB_HOST
              value: postgres
            - name: DB_PASS
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
          image: onfinality/subql-query:latest
          name: graphql-engine
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
