apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: subquery-node
  name: subquery-node
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: subquery-node
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: subquery-node
    spec:
      containers:
        - args:
            - -f=/app
            - --db-schema=app
          env:
            - name: DB_DATABASE
              value: postgres
            - name: DB_HOST
              value: postgres
            - name: DB_PASS
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
          image: intendednull/humanode-subquery-test:latest
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://subquery-node:3000/ready
            failureThreshold: 10
            periodSeconds: 3
            timeoutSeconds: 5
          name: subquery-node
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: subquery-node-claim0
      restartPolicy: Always
      volumes:
        - name: subquery-node-claim0
          persistentVolumeClaim:
            claimName: subquery-node-claim0
status: {}
